name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Installation and tests

    strategy:
      matrix:
        os: [ windows-latest ]
        dc: [ dmd-latest ]
        bt: [ debug ]
        meson: [ '0.62.0' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable MS Developer Command Prompt
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1.7.0

      - name: Install D Compiler and Dub
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Meson Build & Test
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          setup-options: --buildtype=${{ matrix.bt }} -Ddefault_library=static
          meson-version: ${{ matrix.meson }}
          options: --verbose

