name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Installation and tests

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dc: [ dmd-latest ]
        bt: [ debug ]
        meson: [ '0.62.2' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable MS Developer Command Prompt
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1.7.0

      - name: Install Ubuntu deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libzstd-dev

      - name: Install D Compiler and Dub
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Meson Build & Test
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          setup-options: --buildtype=${{ matrix.bt }} -Denable_test=true
          meson-version: ${{ matrix.meson }}
          options: --verbose

      - name: Test Dub package
        run: dub run --arch=x86_64
        working-directory: .github/dub_test

      - name: Test download_unbox Example
        run: ./download_unbox.d
        working-directory: examples

      - name: Test box_upload Example
        run: ./box_upload.d
        working-directory: examples
